using System;using System.Collections;
using System.ComponentModel;
using System.Security.Cryptography.X509Certificates;
using CypherCrescent.Units.Contracts;


namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class AquiferConstant : VariableBase
    {
        public AquiferConstant()
        {
            Name = "AquiferConstant";
        }
        public AquiferConstant(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "AquiferConstant";
        }


        public static implicit operator AquiferConstant(double displayValue) => new AquiferConstant(displayValue);
        public static implicit operator double(AquiferConstant variable) => variable.DatabaseValue ?? 0;
    }
}
        