namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class CGR : VariableBase
    {
        public CGR()
        {
            Name = "CGR";
        }
        public CGR(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "CGR";
        }


        public static implicit operator CGR(double displayValue) => new CGR(displayValue);
        public static implicit operator double(CGR variable) => variable.DatabaseValue ?? 0;
    }
}
        