namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class CondensateAPIGravity : VariableBase
    {
        public CondensateAPIGravity()
        {
            Name = "CondensateAPIGravity";
        }
        public CondensateAPIGravity(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "CondensateAPIGravity";
        }


        public static implicit operator CondensateAPIGravity(double displayValue) => new CondensateAPIGravity(displayValue);
        public static implicit operator double(CondensateAPIGravity variable) => variable.DatabaseValue ?? 0;
    }
}
        