namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ConnateWaterSaturation : VariableBase
    {
        public ConnateWaterSaturation()
        {
            Name = "ConnateWaterSaturation";
        }
        public ConnateWaterSaturation(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ConnateWaterSaturation";
        }


        public static implicit operator ConnateWaterSaturation(double displayValue) => new ConnateWaterSaturation(displayValue);
        public static implicit operator double(ConnateWaterSaturation variable) => variable.DatabaseValue ?? 0;
    }
}
        