namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class DevelopedUltimateRecovery_Gas : VariableBase
    {
        public DevelopedUltimateRecovery_Gas()
        {
            Name = "DevelopedUltimateRecovery_Gas";
        }
        public DevelopedUltimateRecovery_Gas(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "DevelopedUltimateRecovery_Gas";
        }


        public static implicit operator DevelopedUltimateRecovery_Gas(double displayValue) => new DevelopedUltimateRecovery_Gas(displayValue);
        public static implicit operator double(DevelopedUltimateRecovery_Gas variable) => variable.DatabaseValue ?? 0;
    }
}
        