namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class Diffusivity : VariableBase
    {
        public Diffusivity()
        {
            Name = "Diffusivity";
        }
        public Diffusivity(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "Diffusivity";
        }


        public static implicit operator Diffusivity(double displayValue) => new Diffusivity(displayValue);
        public static implicit operator double(Diffusivity variable) => variable.DatabaseValue ?? 0;
    }
}
        