namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class EncroachmentAngle : VariableBase
    {
        public EncroachmentAngle()
        {
            Name = "EncroachmentAngle";
        }
        public EncroachmentAngle(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "EncroachmentAngle";
        }


        public static implicit operator EncroachmentAngle(double displayValue) => new EncroachmentAngle(displayValue);
        public static implicit operator double(EncroachmentAngle variable) => variable.DatabaseValue ?? 0;
    }
}
        