namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class GasRate : VariableBase
    {
        public GasRate()
        {
            Name = "GasRate";
        }
        public GasRate(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "GasRate";
        }


        public static implicit operator GasRate(double displayValue) => new GasRate(displayValue);
        public static implicit operator double(GasRate variable) => variable.DatabaseValue ?? 0;
    }
}
        