namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class GasResIdualFluIdSaturation : VariableBase
    {
        public GasResIdualFluIdSaturation()
        {
            Name = "GasResIdualFluIdSaturation";
        }
        public GasResIdualFluIdSaturation(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "GasResIdualFluIdSaturation";
        }


        public static implicit operator GasResIdualFluIdSaturation(double displayValue) => new GasResIdualFluIdSaturation(displayValue);
        public static implicit operator double(GasResIdualFluIdSaturation variable) => variable.DatabaseValue ?? 0;
    }
}
        