namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class GOR : VariableBase
    {
        public GOR()
        {
            Name = "GOR";
        }
        public GOR(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "GOR";
        }


        public static implicit operator GOR(double displayValue) => new GOR(displayValue);
        public static implicit operator double(GOR variable) => variable.DatabaseValue ?? 0;
    }
}
        