namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class InitialGasInPlace : VariableBase
    {
        public InitialGasInPlace()
        {
            Name = "InitialGasInPlace";
        }
        public InitialGasInPlace(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "InitialGasInPlace";
        }


        public static implicit operator InitialGasInPlace(double displayValue) => new InitialGasInPlace(displayValue);
        public static implicit operator double(InitialGasInPlace variable) => variable.DatabaseValue ?? 0;
    }
}
        