namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class LiquIdRate : VariableBase
    {
        public LiquIdRate()
        {
            Name = "LiquIdRate";
        }
        public LiquIdRate(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "LiquIdRate";
        }


        public static implicit operator LiquIdRate(double displayValue) => new LiquIdRate(displayValue);
        public static implicit operator double(LiquIdRate variable) => variable.DatabaseValue ?? 0;
    }
}
        