namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class MaximumHorizontalStress : VariableBase
    {
        public MaximumHorizontalStress()
        {
            Name = "MaximumHorizontalStress";
        }
        public MaximumHorizontalStress(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "MaximumHorizontalStress";
        }


        public static implicit operator MaximumHorizontalStress(double displayValue) => new MaximumHorizontalStress(displayValue);
        public static implicit operator double(MaximumHorizontalStress variable) => variable.DatabaseValue ?? 0;
    }
}
        