namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class OilRate : VariableBase
    {
        public OilRate()
        {
            Name = "OilRate";
        }
        public OilRate(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "OilRate";
        }


        public static implicit operator OilRate(double displayValue) => new OilRate(displayValue);
        public static implicit operator double(OilRate variable) => variable.DatabaseValue ?? 0;
    }
}
        