namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class OriginalOilInPlace : VariableBase
    {
        public OriginalOilInPlace()
        {
            Name = "OriginalOilInPlace";
        }
        public OriginalOilInPlace(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "OriginalOilInPlace";
        }


        public static implicit operator OriginalOilInPlace(double displayValue) => new OriginalOilInPlace(displayValue);
        public static implicit operator double(OriginalOilInPlace variable) => variable.DatabaseValue ?? 0;
    }
}
        