namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class OuterInnerRadiusRatio : VariableBase
    {
        public OuterInnerRadiusRatio()
        {
            Name = "OuterInnerRadiusRatio";
        }
        public OuterInnerRadiusRatio(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "OuterInnerRadiusRatio";
        }


        public static implicit operator OuterInnerRadiusRatio(double displayValue) => new OuterInnerRadiusRatio(displayValue);
        public static implicit operator double(OuterInnerRadiusRatio variable) => variable.DatabaseValue ?? 0;
    }
}
        