namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class Porosity : VariableBase
    {
        public Porosity()
        {
            Name = "Porosity";
        }
        public Porosity(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "Porosity";
        }


        public static implicit operator Porosity(double displayValue) => new Porosity(displayValue);
        public static implicit operator double(Porosity variable) => variable.DatabaseValue ?? 0;
    }
}
        