namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirLength : VariableBase
    {
        public ReservoirLength()
        {
            Name = "ReservoirLength";
        }
        public ReservoirLength(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirLength";
        }


        public static implicit operator ReservoirLength(double displayValue) => new ReservoirLength(displayValue);
        public static implicit operator double(ReservoirLength variable) => variable.DatabaseValue ?? 0;
    }
}
        