namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirWidth : VariableBase
    {
        public ReservoirWidth()
        {
            Name = "ReservoirWidth";
        }
        public ReservoirWidth(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirWidth";
        }


        public static implicit operator ReservoirWidth(double displayValue) => new ReservoirWidth(displayValue);
        public static implicit operator double(ReservoirWidth variable) => variable.DatabaseValue ?? 0;
    }
}
        