namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirPermeability : VariableBase
    {
        public ReservoirPermeability()
        {
            Name = "ReservoirPermeability";
        }
        public ReservoirPermeability(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirPermeability";
        }


        public static implicit operator ReservoirPermeability(double displayValue) => new ReservoirPermeability(displayValue);
        public static implicit operator double(ReservoirPermeability variable) => variable.DatabaseValue ?? 0;
    }
}
        