namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirOuterRadius : VariableBase
    {
        public ReservoirOuterRadius()
        {
            Name = "ReservoirOuterRadius";
        }
        public ReservoirOuterRadius(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirOuterRadius";
        }


        public static implicit operator ReservoirOuterRadius(double displayValue) => new ReservoirOuterRadius(displayValue);
        public static implicit operator double(ReservoirOuterRadius variable) => variable.DatabaseValue ?? 0;
    }
}
        