namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirDeviationAngle : VariableBase
    {
        public ReservoirDeviationAngle()
        {
            Name = "ReservoirDeviationAngle";
        }
        public ReservoirDeviationAngle(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirDeviationAngle";
        }


        public static implicit operator ReservoirDeviationAngle(double displayValue) => new ReservoirDeviationAngle(displayValue);
        public static implicit operator double(ReservoirDeviationAngle variable) => variable.DatabaseValue ?? 0;
    }
}
        