namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirPressure : VariableBase
    {
        public ReservoirPressure()
        {
            Name = "ReservoirPressure";
        }
        public ReservoirPressure(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirPressure";
        }


        public static implicit operator ReservoirPressure(double displayValue) => new ReservoirPressure(displayValue);
        public static implicit operator double(ReservoirPressure variable) => variable.DatabaseValue ?? 0;
    }
}
        