namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirRadius : VariableBase
    {
        public ReservoirRadius()
        {
            Name = "ReservoirRadius";
        }
        public ReservoirRadius(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirRadius";
        }


        public static implicit operator ReservoirRadius(double displayValue) => new ReservoirRadius(displayValue);
        public static implicit operator double(ReservoirRadius variable) => variable.DatabaseValue ?? 0;
    }
}
        