namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class ReservoirThickness : VariableBase
    {
        public ReservoirThickness()
        {
            Name = "ReservoirThickness";
        }
        public ReservoirThickness(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "ReservoirThickness";
        }


        public static implicit operator ReservoirThickness(double displayValue) => new ReservoirThickness(displayValue);
        public static implicit operator double(ReservoirThickness variable) => variable.DatabaseValue ?? 0;
    }
}
        