namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class SeparatorPressure : VariableBase
    {
        public SeparatorPressure()
        {
            Name = "SeparatorPressure";
        }
        public SeparatorPressure(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "SeparatorPressure";
        }


        public static implicit operator SeparatorPressure(double displayValue) => new SeparatorPressure(displayValue);
        public static implicit operator double(SeparatorPressure variable) => variable.DatabaseValue ?? 0;
    }
}
        