namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class SeparatorCondensateToGasRatio : VariableBase
    {
        public SeparatorCondensateToGasRatio()
        {
            Name = "SeparatorCondensateToGasRatio";
        }
        public SeparatorCondensateToGasRatio(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "SeparatorCondensateToGasRatio";
        }


        public static implicit operator SeparatorCondensateToGasRatio(double displayValue) => new SeparatorCondensateToGasRatio(displayValue);
        public static implicit operator double(SeparatorCondensateToGasRatio variable) => variable.DatabaseValue ?? 0;
    }
}
        