namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class UltimateRecovery_Oil : VariableBase
    {
        public UltimateRecovery_Oil()
        {
            Name = "UltimateRecovery_Oil";
        }
        public UltimateRecovery_Oil(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "UltimateRecovery_Oil";
        }


        public static implicit operator UltimateRecovery_Oil(double displayValue) => new UltimateRecovery_Oil(displayValue);
        public static implicit operator double(UltimateRecovery_Oil variable) => variable.DatabaseValue ?? 0;
    }
}
        