namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class UltimateRecovery_Gas : VariableBase
    {
        public UltimateRecovery_Gas()
        {
            Name = "UltimateRecovery_Gas";
        }
        public UltimateRecovery_Gas(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "UltimateRecovery_Gas";
        }


        public static implicit operator UltimateRecovery_Gas(double displayValue) => new UltimateRecovery_Gas(displayValue);
        public static implicit operator double(UltimateRecovery_Gas variable) => variable.DatabaseValue ?? 0;
    }
}
        