namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class Volume : VariableBase
    {
        public Volume()
        {
            Name = "Volume";
        }
        public Volume(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "Volume";
        }


        public static implicit operator Volume(double displayValue) => new Volume(displayValue);
        public static implicit operator double(Volume variable) => variable.DatabaseValue ?? 0;
    }
}
        