namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class WaterResIdualFluIdSaturation : VariableBase
    {
        public WaterResIdualFluIdSaturation()
        {
            Name = "WaterResIdualFluIdSaturation";
        }
        public WaterResIdualFluIdSaturation(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "WaterResIdualFluIdSaturation";
        }


        public static implicit operator WaterResIdualFluIdSaturation(double displayValue) => new WaterResIdualFluIdSaturation(displayValue);
        public static implicit operator double(WaterResIdualFluIdSaturation variable) => variable.DatabaseValue ?? 0;
    }
}
        