namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class WaterCut : VariableBase
    {
        public WaterCut()
        {
            Name = "WaterCut";
        }
        public WaterCut(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "WaterCut";
        }


        public static implicit operator WaterCut(double displayValue) => new WaterCut(displayValue);
        public static implicit operator double(WaterCut variable) => variable.DatabaseValue ?? 0;
    }
}
        