namespace CypherCrescent.Units.Variables
{
    /*
     * ===================================================================================
     * THIS IS AN AUTOGENERATED CLASS FROM THE CYPHERCRESCENT VARIABLE SYSTEM. 
     * CHANGES TO THIS FILE WILL BE OVERWRITTEN BY NEWER FILE GENERATIONS.
     * ===================================================================================
     */
    public sealed class WGR : VariableBase
    {
        public WGR()
        {
            Name = "WGR";
        }
        public WGR(double displayValue):base()
        {
            DatabaseValue = displayValue;
            Name = "WGR";
        }


        public static implicit operator WGR(double displayValue) => new WGR(displayValue);
        public static implicit operator double(WGR variable) => variable.DatabaseValue ?? 0;
    }
}
        