name: 'PR opened action'

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Run tests
        run: dotnet test --verbosity normal

      - name: Publish
        run: dotnet publish -c Release --self-contained -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
        env:
          PROJECT-PATH: 'WindowsClient/WindowsClient/WindowsClient.csproj'

      - name: Create a Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload to Release
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upload-url: ${{ steps.create_release.outputs.upload_url }}
          asset-path: 'WindowsClient/bin/Release/net5.0-windows/win-x64/publish/'
          asset-name: 'app.exe'
