name: PR opened action"

on:
  pull_request_review:
    types: [submitted]

env:
  PROJECT-PATH: WindowsClient/WindowsClient/WindowsClient.sln

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install .Net core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT-PATH}}

    - name: Build
      run:  dotnet build ${{ env.PROJECT-PATH }} -c Release --no-restore 

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish 
      run: dotnet publish ${{env.PROJECT-PATH}} -c Release --self-contained -r win-x64
